name: Lint

on: 
  push: 
    branches: [ "master" ]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v2
        with:
          go-version: '1.20'
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
          HUSKY_SKIP_INSTALL: true
      - uses: tinovyatkin/action-eslint@v1
        with:
          check-name: eslint # this is the check name from above 👆 where to post annotations